import { useMemo,useState } from "react";
const nums=(x=[])=>x.map(v=>Number(typeof v==="number"?v:v?.quote??v?.price??v?.value??0)).filter(Number.isFinite);
function candles(values,n){const x=nums(values).slice(-240),out=[];for(let i=0;i<x.length;i+=n){const g=x.slice(i,i+n);if(g.length)out.push({open:g[0],high:Math.max(...g),low:Math.min(...g),close:g.at(-1)});}return out.slice(-55);}
export default function QuantumTradingChart({prices=[],analysis={}}){
 const [n,setN]=useState(5),c=useMemo(()=>candles(prices,n),[prices,n]);
 if(c.length<3)return <section className="quantumTradingChart"><small>TRADINGVIEW-STYLE MARKET VIEW</small><h3>Collecting candles...</h3></section>;
 const w=1200,h=340,p=24,min=Math.min(...c.map(v=>v.low)),max=Math.max(...c.map(v=>v.high)),r=Math.max(1e-9,max-min),step=(w-p*2)/c.length,y=v=>p+((max-v)/r)*(h-p*2);
 return <section className="quantumTradingChart"><header><div><small>TRADINGVIEW-STYLE MARKET VIEW</small><h3>Five-AI live candlestick chart</h3></div><div className="quantumChartControls">{[3,5,10].map(v=><button key={v} className={n===v?"active":""} onClick={()=>setN(v)}>{v}T candle</button>)}</div></header><div className="quantumFiveAI">{(analysis.fiveAI?.models||[]).map(m=><article key={m.name} className={m.signal.toLowerCase()}><span>{m.name}</span><strong>{m.signal}</strong><b>{m.confidence.toFixed(0)}%</b><small>{m.reason}</small></article>)}</div><div className="quantumChartCanvas"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">{[.2,.4,.6,.8].map(q=><line key={q} x1={p} x2={w-p} y1={h*q} y2={h*q} className="quantumChartGrid"/>)}{c.map((v,i)=>{const x=p+i*step+step/2,up=v.close>=v.open,top=y(Math.max(v.open,v.close)),bottom=y(Math.min(v.open,v.close));return <g key={i} className={`quantumCandle ${up?"rise":"fall"}`}><line x1={x} x2={x} y1={y(v.high)} y2={y(v.low)}/><rect x={x-Math.max(4,Math.min(13,step*.56))/2} y={top} width={Math.max(4,Math.min(13,step*.56))} height={Math.max(2,bottom-top)}/></g>})}</svg></div><footer><strong>Agreement {analysis.fiveAI?.agreement||0}/5</strong><span>Candidate {analysis.fiveAI?.candidate||"WAIT"}</span><span>{analysis.displayDuration||"WAIT"}</span></footer></section>;
}
