import {useEffect,useMemo,useRef,useState} from 'react';
import useDerivTicks from '../hooks/useDerivTicks';
import {analyzeRiseFall} from '../analysis/riseFallEngine';
import {createRiskManager} from '../bot/riskManager';
import '../styles/RiseFallBot.css';
const pct=v=>`${Number(v||0).toFixed(1)}%`,money=v=>Number(v||0).toFixed(2);
const idOf=v=>String(v?.contract_id||v?.contractId||v?.id||v?.buy?.contract_id||v?.proposal_open_contract?.contract_id||'');
const profitOf=v=>{const d=Number(v?.profit??v?.profit_loss??v?.pnl);if(Number.isFinite(d))return d;return Number(v?.sell_price||v?.payout||0)-Number(v?.buy_price||v?.purchase_price||0)};
const settled=v=>Boolean(v?.is_sold||v?.is_expired||['won','lost','sold','expired','settled'].includes(String(v?.status||v?.contract_status||'').toLowerCase()));
export default function RiseFallBot(){
 const{markets=[],market=null,symbol='',status='DISCONNECTED',statusDetail='',connected=false,authenticatedFeed=false,selectedAccountType='demo',prices=[],currentPrice=null,openContracts=[],tradeBusy=false,tradeError='',connect,disconnect,changeSymbol,placeTrade}=useDerivTicks();
 const[running,setRunning]=useState(false),[autoExecute,setAutoExecute]=useState(false),[allowReal,setAllowReal]=useState(false),[stake,setStake]=useState(.35),[duration,setDuration]=useState(5),[message,setMessage]=useState('Scanner ready.'),[settingsOpen,setSettingsOpen]=useState(false);
 const riskRef=useRef(createRiskManager()),busyRef=useRef(false),runningRef=useRef(false),processedRef=useRef(new Set());
 const analysis=useMemo(()=>analyzeRiseFall(prices,{minimumSamples:60,minimumConfidence:68}),[prices]);const risk=riskRef.current.snapshot();
 useEffect(()=>{runningRef.current=running},[running]);
 useEffect(()=>{for(const c of openContracts){if(!settled(c))continue;const id=idOf(c);if(!id||processedRef.current.has(id))continue;processedRef.current.add(id);riskRef.current.onResult(id,profitOf(c));}},[openContracts]);
 const execute=async()=>{if(busyRef.current)return;if(!connected||!authenticatedFeed){setMessage('Connect the authenticated Deriv feed first.');return}if(analysis.signal==='WAIT'||!analysis.ready){setMessage('No qualified Rise/Fall signal.');return}if(String(selectedAccountType).toLowerCase()==='real'&&!allowReal){setMessage('REAL ACCOUNT LOCKED.');return}const gate=riskRef.current.canTrade();if(!gate.ok){setMessage(gate.reason);return}busyRef.current=true;setMessage(`Executing ${analysis.signal} ${analysis.confidence}%...`);try{const r=await placeTrade({contractType:analysis.contractType,amount:Number(stake),basis:'stake',duration:Number(duration),durationUnit:'t',symbol});const id=idOf(r);riskRef.current.onEntry(id);setMessage(`${analysis.signal} opened ${id?'#'+id:''}`)}catch(e){setMessage(e instanceof Error?e.message:'Trade failed.')}finally{busyRef.current=false}};
 useEffect(()=>{if(!running||!autoExecute||!analysis.ready||analysis.signal==='WAIT')return;void execute()},[analysis,autoExecute,running]);
 const toggle=()=>{if(running){setRunning(false);setAutoExecute(false);setMessage('Bot stopped.')}else{riskRef.current.reset();processedRef.current.clear();setRunning(true);setMessage('Bot scanning live ticks.')}};
 const wr=risk.wins+risk.losses?risk.wins/(risk.wins+risk.losses)*100:0,price=Number.isFinite(currentPrice)?currentPrice.toFixed(market?.decimals??3):'—',real=String(selectedAccountType).toLowerCase()==='real';
 return <section className='rfBot'>
  <div className='rfBotTop'><div><small>DERIV • RISE / FALL ENGINE</small><h1>Pulse Rise/Fall</h1><p>Momentum + trend + volatility filter</p></div><div className='rfConnection'><span className={connected?'rfDot live':'rfDot'}/>{connected?'LIVE':status}</div></div>
  <div className='rfControls'><select value={symbol} disabled={!connected} onChange={e=>void changeSymbol(e.target.value)}>{markets.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button onClick={()=>connected?disconnect():connect()}>{connected?'Disconnect':'Connect'}</button><button className={running?'danger':'primary'} onClick={toggle}>{running?'STOP BOT':'START BOT'}</button></div>
  <div className='rfMain'><div className='rfSignal'><div className='rfSignalHeader'><div><small>{market?.label||symbol||'MARKET'}</small><strong>{price}</strong></div><div className={`rfDirection ${analysis.signal==='RISE'?'rise':analysis.signal==='FALL'?'fall':''}`}>{analysis.signal}</div></div><div className='rfMeter'><div className='rfMeterFill' style={{width:`${Math.max(2,analysis.confidence||0)}%`}}/></div><div className='rfProb'><span><b>RISE</b> {analysis.signal==='RISE'?pct(analysis.confidence):'—'}</span><span><b>FALL</b> {analysis.signal==='FALL'?pct(analysis.confidence):'—'}</span></div><div className='rfConfidence'><small>MODEL CONFIDENCE</small><strong>{analysis.ready?pct(analysis.confidence):'WAIT'}</strong></div><p className='rfReason'>{analysis.reason}</p><button className='rfTradeButton' disabled={tradeBusy||!analysis.ready||analysis.signal==='WAIT'} onClick={()=>void execute()}>{tradeBusy?'EXECUTING...':`TRADE ${analysis.signal}`}</button></div>
  <div className='rfSide'><div className='rfGrid'><Metric label='TREND' value={analysis.trend||'WAIT'}/><Metric label='MOMENTUM' value={analysis.momentum||'WAIT'}/><Metric label='VOLATILITY' value={analysis.volatility||'WAIT'}/><Metric label='AGREEMENT' value={analysis.ready?`${analysis.agreement}/4`:'—'}/></div><div className='rfStats'><span><small>Session P/L</small><b>{money(risk.sessionPnl)}</b></span><span><small>Win rate</small><b>{pct(wr)}</b></span><span><small>Trades</small><b>{risk.trades}/10</b></span><span><small>Stake</small><b>${Number(stake).toFixed(2)}</b></span></div></div></div>
  <div className='rfBottom'><label className='rfToggle'><input type='checkbox' checked={autoExecute} onChange={e=>setAutoExecute(e.target.checked)} disabled={!running}/> AUTO EXECUTE</label><label>Stake <input type='number' min='.35' step='.01' value={stake} onChange={e=>setStake(Math.max(.35,Number(e.target.value)||.35))}/></label><label>Ticks <select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[1,2,3,5,8,10].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className='rfToggle'><input type='checkbox' checked={allowReal} onChange={e=>setAllowReal(e.target.checked)} disabled={!real}/> ALLOW REAL</label><button className='rfSettings' onClick={()=>setSettingsOpen(v=>!v)}>{settingsOpen?'HIDE':'RISK'}</button></div>
  {settingsOpen&&<div className='rfRiskPanel'><span>Max session loss <b>$3.00</b></span><span>Max trades <b>10</b></span><span>Max open <b>1</b></span><span>2 losses <b>60s pause</b></span><span>Stake <b>FIXED</b></span></div>}
  <div className='rfStatus'><span>{running?'● SCANNING':'○ READY'}</span><span>{message}</span></div>{(statusDetail||tradeError)&&<div className='rfError'>{tradeError||statusDetail}</div>}
 </section>}
function Metric({label,value}){return <div className='rfMetric'><small>{label}</small><strong>{value}</strong></div>}
